In [17]:
from cvxopt import matrix, solvers

In [10]:
n=3

In [2]:
a = np.array([.25, .5, .25])
b = np.array([.3, .3, .4])
vecs = np.array([0, 1, 2])

In [5]:
C =  np.sqrt((vecs[:,np.newaxis] - vecs)**2)

In [6]:
C

array([[ 0.,  1.,  2.],
       [ 1.,  0.,  1.],
       [ 2.,  1.,  0.]])

In [8]:
c = C.flatten('F')

In [9]:
np.concatenate([a, b])

array([ 0.25,  0.5 ,  0.25,  0.3 ,  0.3 ,  0.4 ])

In [18]:
A = np.vstack([np.kron(np.ones(n)[np.newaxis,:], np.eye(n)),
                np.kron(np.eye(n), np.ones(n)[np.newaxis,:])])

In [27]:
A

array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.]])

In [34]:
np.linalg.linalg.matrix_rank(A[:-1,:])

5

In [28]:
c_mat = matrix(c)
A_mat = matrix(A[:-1,:])
b_mat = matrix(np.concatenate([a, b])[:-1])

In [30]:
c_mat

<9x1 matrix, tc='d'>

In [31]:
A_mat

<5x9 matrix, tc='d'>

In [32]:
b_mat

<5x1 matrix, tc='d'>

In [41]:
solvers.lp(c_mat, A_mat, b_mat)

ValueError: Rank(A) < p or Rank([G; A]) < n