In [1]:
from cvxopt import matrix, solvers
from scipy.optimize import linprog

In [2]:
a = np.array([.6, .4])
b = np.array([.5, .4, .1])
vecs_a = np.array([0, 3.5])
vecs_b = np.array([1, 2, 3])

In [3]:
n, m = len(a), len(b)

In [4]:
C =  np.sqrt((vecs_a[:,np.newaxis] - vecs_b)**2)
#C = np.array([[1, 2, 3], [5, 6, 7.5]], dtype=float)

In [5]:
C

array([[ 1. ,  2. ,  3. ],
       [ 2.5,  1.5,  0.5]])

In [6]:
c = C.flatten('F')

In [7]:
A = np.vstack([np.kron(np.eye(n), np.ones(m)[np.newaxis,:]),
               np.kron(np.ones(n)[np.newaxis,:], np.eye(m))])

In [8]:
np.linalg.linalg.matrix_rank(A[:-1,:])

4

In [9]:
c_mat = matrix(c)
A_mat = matrix(A[:-1,:])
b_mat = matrix(np.concatenate([a,b])[:-1])
G_mat = matrix(-np.eye(n*m))
h_mat = matrix(np.zeros(n*m))

In [10]:
c_mat

<6x1 matrix, tc='d'>

In [11]:
A_mat

<4x6 matrix, tc='d'>

In [12]:
G_mat

<6x6 matrix, tc='d'>

In [13]:
b_mat

<4x1 matrix, tc='d'>

In [14]:
sol = solvers.lp(c_mat, G_mat, h_mat, A=A_mat, b=b_mat)

     pcost       dcost       gap    pres   dres   k/t
 0:  1.8667e+00  1.8667e+00  2e+00  1e-16  9e-01  1e+00
 1:  1.7017e+00  1.6024e+00  5e-01  8e-17  2e-01  1e-01
 2:  1.7002e+00  1.6990e+00  6e-03  2e-16  2e-03  2e-03
 3:  1.7000e+00  1.7000e+00  6e-05  1e-16  2e-05  2e-05
 4:  1.7000e+00  1.7000e+00  6e-07  3e-16  2e-07  2e-07
 5:  1.7000e+00  1.7000e+00  6e-09  4e-16  2e-09  2e-09
Optimal solution found.


In [15]:
A

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  1.]])

In [16]:
np.concatenate([a,b])

array([ 0.6,  0.4,  0.5,  0.4,  0.1])

In [17]:
C

array([[ 1. ,  2. ,  3. ],
       [ 2.5,  1.5,  0.5]])

In [18]:
np.array(sol['x']).reshape((n,m)).round(2)

array([[ 0.33,  0.27,  0.  ],
       [ 0.17,  0.13,  0.1 ]])

In [19]:
np.array(sol['x']).round(2)

array([[ 0.33],
       [ 0.27],
       [ 0.  ],
       [ 0.17],
       [ 0.13],
       [ 0.1 ]])

In [20]:
matrix(np.zeros((1,n*m)))

<1x6 matrix, tc='d'>

In [21]:
matrix(np.zeros(1))

<1x1 matrix, tc='d'>

In [22]:
def opt_lp(a, b, a_vec=None, b_vec=None, C=None):
    if C is None:
        if len(a_vec.shape) == 1:
            C =  np.sqrt((vecs_a[:,np.newaxis] - vecs_b)**2)
        else:
            distances_sq = (vecs_a[:,np.newaxis] - vecs_b)**2
            C = np.sqrt(distances_sq.sum(-1))
    c = C.flatten('F')
    A = np.vstack([np.kron(np.eye(n), np.ones(m)[np.newaxis,:]),
               np.kron(np.ones(n)[np.newaxis,:], np.eye(m))])
    
    c_mat = matrix(c)
    A_mat = matrix(A[:-1,:])
    b_mat = matrix(np.concatenate([a,b])[:-1])
    G_mat = matrix(-np.eye(n*m))
    h_mat = matrix(np.zeros(n*m))
    
    sol = solvers.lp(c_mat, G_mat, h_mat, A=A_mat, b=b_mat)
    return sol

In [352]:
a_vec = np.array([[0,0], [1,1]])
b_vec = np.array([[0,1], [1,0]])

ValueError: bad axis1 argument to swapaxes

In [355]:
distances_sq

array([[ 1.  ,  4.  ,  9.  ],
       [ 6.25,  2.25,  0.25]])

In [349]:
opt_lp(a, b, a_vec=vecs_a, b_vec=vecs_b)

     pcost       dcost       gap    pres   dres   k/t
 0:  1.8667e+00  1.8667e+00  2e+00  1e-16  9e-01  1e+00
 1:  1.7017e+00  1.6024e+00  5e-01  8e-17  2e-01  1e-01
 2:  1.7002e+00  1.6990e+00  6e-03  2e-16  2e-03  2e-03
 3:  1.7000e+00  1.7000e+00  6e-05  1e-16  2e-05  2e-05
 4:  1.7000e+00  1.7000e+00  6e-07  3e-16  2e-07  2e-07
 5:  1.7000e+00  1.7000e+00  6e-09  4e-16  2e-09  2e-09
Optimal solution found.


{'dual infeasibility': 2.277671412534351e-09,
 'dual objective': 1.699999998990706,
 'dual slack': 1.54488706399777e-09,
 'gap': 5.595562933791835e-09,
 'iterations': 5,
 'primal infeasibility': 4.191000011634393e-16,
 'primal objective': 1.7000000001511417,
 'primal slack': 7.557048828022301e-11,
 'relative gap': 3.29150761006702e-09,
 'residual as dual infeasibility certificate': None,
 'residual as primal infeasibility certificate': None,
 's': <6x1 matrix, tc='d'>,
 'status': 'optimal',
 'x': <6x1 matrix, tc='d'>,
 'y': <4x1 matrix, tc='d'>,
 'z': <6x1 matrix, tc='d'>}